import type { BuildCapability, BuildStatusNode, BuildSummaryCard } from '../model/types';

const DOC_ROOT = '/Users/joker/code/quant-trading-assistant';

export const buildSummaryCards: BuildSummaryCard[] = [
  {
    title: '总体成熟度',
    value: 'M4.0',
    description: '核心交易记录、盈亏账本和实际持仓盘点已形成闭环',
    status: 'DONE',
  },
  {
    title: '当前最优先',
    value: 'P1 行情数据基础',
    description: 'v0.1.1 交易闭环优化已验收，下一阶段按 MARKET_DATA_FOUNDATION_DESIGN 建设证券主数据与日 K 边界',
    status: 'TODO',
  },
  {
    title: '数据可信度',
    value: '核心记录与盘点可落库',
    description: '自选、计划、交易、复盘、账本和持仓快照均支持 remote DB',
    status: 'DONE',
  },
  {
    title: '交易闭环完整度',
    value: '计划→交易→账本→盘点→复盘',
    description: '理论账本和实际持仓盘点均已具备可追溯记录',
    status: 'DONE',
  },
];

export const buildCapabilities: BuildCapability[] = [
  {
    id: 'data-accumulation',
    title: '数据沉淀',
    current: '自选、计划、交易、复盘、账本和持仓快照均可落库',
    target: '增加批量导入和周期归档',
    score: 88,
  },
  {
    id: 'pnl-explainability',
    title: '盈亏解释',
    current: 'FIFO 账本与实际持仓快照可分别追溯',
    target: '增加理论持仓与实际快照差异对比',
    score: 82,
  },
  {
    id: 'risk-control',
    title: '风险控制',
    current: '已有仓位计算器和交易风险提示',
    target: '增加组合级风险和周期提醒',
    score: 58,
  },
  {
    id: 'review-loop',
    title: '复盘闭环',
    current: '可记录计划执行、情绪、错误标签',
    target: '形成周/月周期复盘报告',
    score: 64,
  },
  {
    id: 'input-automation',
    title: '自动化录入',
    current: '图片识别已调研，尚未正式接入',
    target: '截图识别生成可编辑草稿',
    score: 22,
  },
];

export const buildStatusTree: BuildStatusNode[] = [
  {
    id: 'foundation',
    title: '数据与基础设施',
    category: '基础设施',
    priority: 'P0',
    status: 'DONE',
    maturity: 'M4',
    progress: 82,
    productValue: '让系统具备稳定开发、部署、落库和 AI 协作基础。',
    currentEvidence: ['Spring Boot + MyBatis 后端已成形', 'React 前端已成形', 'AI 开发文档和 skills 已沉淀'],
    nextActions: ['保持文档、测试和部署口径同步'],
    backendState: '基础 API、Flyway、MyBatis、测试已具备',
    frontendState: '基础布局、路由、mock/remote adapter 已具备',
    dataOwnership: 'DB',
    risks: ['生产数据模式和本地模式文案仍需持续保持一致'],
    docLinks: [
      { label: 'AI Development Index', path: `${DOC_ROOT}/docs/AI_DEVELOPMENT_INDEX.md` },
      { label: 'Current Architecture', path: `${DOC_ROOT}/docs/CURRENT_ARCHITECTURE_AND_MODULES.md` },
    ],
    children: [
      {
        id: 'backend-foundation',
        title: '后端基础框架',
        category: '基础设施',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M4',
        progress: 90,
        productValue: '支撑所有交易记录、复盘、账本数据落库。',
        currentEvidence: ['Spring Boot 项目可测试', 'MyBatis XML SQL 已使用', 'Flyway migration 已使用'],
        nextActions: ['新模块继续补 manager/service/controller/mapper 测试'],
        backendState: '已验收可用',
        frontendState: '无直接影响',
        dataOwnership: 'DB',
        risks: [],
        docLinks: [{ label: 'Build Checklist', path: `${DOC_ROOT}/docs/BUILD_CHECKLIST.md` }],
      },
      {
        id: 'frontend-foundation',
        title: '前端工程框架',
        category: '基础设施',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M4',
        progress: 84,
        productValue: '支撑日常使用页面、API 切换和服务器部署。',
        currentEvidence: ['React + Vite + TypeScript', 'Ant Design 布局', 'mock/remote 双模式'],
        nextActions: ['新页面保持 typecheck/lint/test/build'],
        backendState: '不涉及',
        frontendState: '已验收可用',
        dataOwnership: 'LOCAL_STORAGE',
        risks: ['本地模式数据不会自动同步 DB'],
        docLinks: [{ label: 'Frontend Architecture', path: `${DOC_ROOT}/docs/FRONTEND_ARCHITECTURE.md` }],
      },
      {
        id: 'production-data-mode',
        title: '生产部署和数据模式',
        category: '基础设施',
        priority: 'P0',
        status: 'RISK',
        maturity: 'M3',
        progress: 62,
        productValue: '保证正式使用时数据进入后端 DB，而不是散落在浏览器。',
        currentEvidence: ['apiBaseUrl 留空可走同源 /api/v1', '前端支持 remote 模式'],
        nextActions: ['确认生产默认 remote', '部署后验收 Nginx /api 反代'],
        backendState: '可支撑',
        frontendState: '需要持续校验文案和默认模式',
        dataOwnership: 'DB',
        risks: ['用户若误用本地模式，数据只在当前浏览器'],
        docLinks: [{ label: 'Product Blueprint', path: `${DOC_ROOT}/docs/PRODUCT_BLUEPRINT.md` }],
      },
      {
        id: 'ai-collaboration-docs',
        title: 'AI 协作文档与 skills',
        category: '基础设施',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M4',
        progress: 88,
        productValue: '让 Claude/Codex/OpenClaw 后续开发有统一入口和验收规则。',
        currentEvidence: ['产品、后端、前端、验收四个 skill 已沉淀', '总入口文档已推送'],
        nextActions: ['每次新模块完成后同步 checklist'],
        backendState: '文档已就绪',
        frontendState: '文档已就绪',
        dataOwnership: 'NONE',
        risks: [],
        docLinks: [{ label: 'Skill Usage', path: `${DOC_ROOT}/docs/ai/SKILL_USAGE.md` }],
      },
    ],
  },
  {
    id: 'trade-loop',
    title: '交易记录闭环',
    category: '交易闭环',
    priority: 'P0',
    status: 'DONE',
    maturity: 'M4',
    progress: 78,
    productValue: '把盘前计划、真实交易、盘后复盘串成可回看的纪律闭环。',
    currentEvidence: ['自选股、交易计划、交易记录、复盘已有 API 和页面基础'],
    nextActions: ['增强计划与交易记录关联', '补周期复盘报告'],
    backendState: '核心 CRUD 已完成',
    frontendState: '核心页面已完成',
    dataOwnership: 'DB',
    risks: ['本地模式和后端模式不会自动同步'],
    docLinks: [{ label: 'Today MVP API', path: `${DOC_ROOT}/docs/API_TODAY_MVP.md` }],
    children: [
      {
        id: 'watchlist',
        title: '自选股',
        category: '交易闭环',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M4',
        progress: 82,
        productValue: '记录关注池、风格、关注理由和风险位。',
        currentEvidence: ['Watchlist CRUD 已有', '支持启用/停用'],
        nextActions: ['优化筛选和分组体验'],
        backendState: 'API 完成',
        frontendState: '页面完成',
        dataOwnership: 'DB',
        risks: [],
        docLinks: [{ label: 'API Today MVP', path: `${DOC_ROOT}/docs/API_TODAY_MVP.md` }],
      },
      {
        id: 'trade-plan',
        title: '交易计划',
        category: '交易闭环',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M4',
        progress: 80,
        productValue: '盘前明确允许交易条件、止损和计划仓位。',
        currentEvidence: ['交易计划 CRUD 已有', '允许交易时有必填约束'],
        nextActions: ['和交易记录建立更强关联'],
        backendState: 'API 完成',
        frontendState: '页面完成',
        dataOwnership: 'DB',
        risks: [],
        docLinks: [{ label: 'Product Blueprint', path: `${DOC_ROOT}/docs/PRODUCT_BLUEPRINT.md` }],
      },
      {
        id: 'trade-journal',
        title: '交易记录',
        category: '交易闭环',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M4',
        progress: 82,
        productValue: '记录每一笔真实买卖、原因、费用、情绪和复盘状态。',
        currentEvidence: ['交易流水 CRUD 已有', '费用字段和复盘状态已覆盖'],
        nextActions: ['继续确认费用口径和批量复盘体验'],
        backendState: 'API 完成',
        frontendState: '页面完成',
        dataOwnership: 'DB',
        risks: ['费用录入错误会影响账本盈亏'],
        docLinks: [{ label: 'Portfolio API', path: `${DOC_ROOT}/docs/api/PORTFOLIO_API.md` }],
      },
      {
        id: 'review',
        title: '盘后复盘',
        category: '交易闭环',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M4',
        progress: 76,
        productValue: '沉淀做对、做错和下一步规则修正。',
        currentEvidence: ['复盘 CRUD 已有', '可关联交易记录'],
        nextActions: ['增加周/月复盘报告'],
        backendState: 'API 完成',
        frontendState: '页面完成',
        dataOwnership: 'DB',
        risks: [],
        docLinks: [{ label: 'Product Blueprint', path: `${DOC_ROOT}/docs/PRODUCT_BLUEPRINT.md` }],
      },
      {
        id: 'dashboard-aggregation',
        title: '工作台聚合与待办中心',
        category: '交易闭环',
        priority: 'P1',
        status: 'DONE',
        maturity: 'M4',
        progress: 90,
        productValue: '一屏看到今日计划、交易、待复盘风险和结构化待办（待复盘/未关联计划/缺少止损/快照过期/对账差异）。',
        currentEvidence: [
          '后端 /dashboard/today 增加结构化 todos 聚合',
          '前端 remote 直接用后端聚合，mock 用同口径纯函数',
          '待办按 RISK/WARNING/INFO 排序并可跳转',
        ],
        nextActions: ['后续接入行情后可补充行情类提醒'],
        backendState: '聚合 API 含 todos，测试通过',
        frontendState: '待办中心组件 + dashboard 编排完成',
        dataOwnership: 'DERIVED',
        risks: ['聚合结果依赖各模块数据质量'],
        docLinks: [{ label: 'Current Architecture', path: `${DOC_ROOT}/docs/CURRENT_ARCHITECTURE_AND_MODULES.md` }],
      },
    ],
  },
  {
    id: 'portfolio-pnl',
    title: '持仓与盈亏',
    category: '持仓盈亏',
    priority: 'P0',
    status: 'IN_PROGRESS',
    maturity: 'M4',
    progress: 82,
    productValue: '让用户知道持仓、已结算交易、浮盈亏和实际持仓盘点。',
    currentEvidence: ['FIFO 交易账本已完成', '持仓快照 DB、API、手工录入和历史查询已验收'],
    nextActions: ['设计快照差异对比', '接入图片识别草稿'],
    backendState: '账本与快照 API 完成',
    frontendState: '账本与快照页面完成',
    dataOwnership: 'DB',
    risks: ['快照仍依赖用户手工盘点，尚未自动对比理论持仓'],
    docLinks: [{ label: 'Position Snapshot Design', path: `${DOC_ROOT}/docs/features/POSITION_SNAPSHOT_DESIGN.md` }],
    children: [
      {
        id: 'portfolio-ledger',
        title: '交易账本 FIFO',
        category: '持仓盈亏',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M4',
        progress: 84,
        productValue: '基于交易流水自动计算理论持仓、已结算盈亏和胜率。',
        currentEvidence: ['FIFO 计算器、portfolio API、前端账本页面已存在'],
        nextActions: ['后续和持仓快照做差异核对'],
        backendState: 'API 完成',
        frontendState: '页面完成',
        dataOwnership: 'DERIVED',
        risks: ['依赖交易流水完整性'],
        docLinks: [{ label: 'Portfolio API', path: `${DOC_ROOT}/docs/api/PORTFOLIO_API.md` }],
      },
      {
        id: 'price-snapshot',
        title: '当前价维护',
        category: '持仓盈亏',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M3',
        progress: 70,
        productValue: '手工维护当前价，用于估算浮动盈亏。',
        currentEvidence: ['portfolio_price_snapshot 表和维护入口已存在'],
        nextActions: ['优化批量维护体验'],
        backendState: 'API 完成',
        frontendState: '页面完成',
        dataOwnership: 'DB',
        risks: ['当前价不是实时行情，依赖用户手工维护'],
        docLinks: [{ label: 'Portfolio API', path: `${DOC_ROOT}/docs/api/PORTFOLIO_API.md` }],
      },
      {
        id: 'position-snapshot',
        title: '持仓快照',
        category: '持仓盈亏',
        priority: 'P0',
        status: 'DONE',
        maturity: 'M4',
        progress: 100,
        productValue: '像每日盘点库存一样，记录某时点券商账户实际持仓。',
        currentEvidence: ['Flyway V4 双表', '草稿/确认/作废 API', '手工录入与历史详情页面', 'MySQL 真实联调通过'],
        nextActions: ['增加快照对比', '图片识别结果复用草稿 API'],
        backendState: 'DB、API、测试完成',
        frontendState: '页面、双模式、测试和响应式验收完成',
        dataOwnership: 'DB',
        risks: ['数据准确性取决于用户录入与确认'],
        docLinks: [
          { label: 'Position Snapshot Design', path: `${DOC_ROOT}/docs/features/POSITION_SNAPSHOT_DESIGN.md` },
          { label: 'Position Snapshot API', path: `${DOC_ROOT}/docs/api/POSITION_SNAPSHOT_API.md` },
        ],
      },
      {
        id: 'snapshot-comparison',
        title: '快照对比与账本对账',
        category: '持仓盈亏',
        priority: 'P1',
        status: 'DONE',
        maturity: 'M4',
        progress: 100,
        productValue: '比较两次持仓盘点，并与截止时点 FIFO 账本对账，定位实际与理论差异。',
        currentEvidence: [
          '后端 comparison/reconciliation API + 纯计算 Manager + 单测',
          '前端对比/对账 Drawer + mock 纯函数（与后端口径一致）+ remote adapter',
          'curl 端到端联调通过',
        ],
        nextActions: ['后续接入行情后可扩展市值重估'],
        backendState: 'API、计算、测试完成',
        frontendState: '对比/对账视图与双模式 adapter 完成',
        dataOwnership: 'DERIVED',
        risks: ['对账只读，不会自动修正交易流水'],
        docLinks: [
          { label: 'Position Snapshot API', path: `${DOC_ROOT}/docs/api/POSITION_SNAPSHOT_API.md` },
          { label: 'Trade Workflow Design', path: `${DOC_ROOT}/docs/features/TRADE_WORKFLOW_OPTIMIZATION_DESIGN.md` },
        ],
      },
    ],
  },
  {
    id: 'ai-input',
    title: '智能录入',
    category: '智能录入',
    priority: 'P1',
    status: 'TODO',
    maturity: 'M1',
    progress: 18,
    productValue: '减少手工录入成本，但所有识别结果必须可编辑确认。',
    currentEvidence: ['GLM/OCR 可行性已调研', '图片识别原则已沉淀'],
    nextActions: ['设计图片粘贴和可编辑识别草稿'],
    backendState: '未开始',
    frontendState: '未开始',
    dataOwnership: 'EXTERNAL',
    risks: ['截图可能包含隐私', 'AI 可能识别错数字、小数点、负号'],
    docLinks: [{ label: 'Product Blueprint', path: `${DOC_ROOT}/docs/PRODUCT_BLUEPRINT.md` }],
    children: [
      {
        id: 'image-recognition-research',
        title: '图片识别调研',
        category: '智能录入',
        priority: 'P1',
        status: 'DONE',
        maturity: 'M1',
        progress: 25,
        productValue: '确认图片识别适合作为持仓快照自动填表能力。',
        currentEvidence: ['已明确 Coding Plan 与普通 API 权益要区分'],
        nextActions: ['落地时确认实际 API Key 和模型计费'],
        backendState: '调研完成',
        frontendState: '调研完成',
        dataOwnership: 'EXTERNAL',
        risks: ['不要把 Coding Plan 误认为线上 API 额度'],
        docLinks: [{ label: 'Product Blueprint', path: `${DOC_ROOT}/docs/PRODUCT_BLUEPRINT.md` }],
      },
      {
        id: 'image-upload',
        title: '图片上传/粘贴',
        category: '智能录入',
        priority: 'P1',
        status: 'TODO',
        maturity: 'M0',
        progress: 0,
        productValue: '让用户贴券商持仓截图，减少逐行录入。',
        currentEvidence: ['持仓快照页面和草稿机制已完成'],
        nextActions: ['设计粘贴、预览、隐私提示'],
        backendState: '未开始',
        frontendState: '未开始',
        dataOwnership: 'NONE',
        risks: ['需要明确不上传账户隐私'],
        docLinks: [{ label: 'Position Snapshot Design', path: `${DOC_ROOT}/docs/features/POSITION_SNAPSHOT_DESIGN.md` }],
      },
      {
        id: 'ai-draft',
        title: 'AI 识别草稿',
        category: '智能录入',
        priority: 'P1',
        status: 'TODO',
        maturity: 'M0',
        progress: 0,
        productValue: '把截图识别成可编辑持仓快照草稿。',
        currentEvidence: ['provider 设计待做'],
        nextActions: ['后端封装 mock provider，再接 GLM/OCR provider'],
        backendState: '未开始',
        frontendState: '未开始',
        dataOwnership: 'EXTERNAL',
        risks: ['识别结果不能直接确认入库'],
        docLinks: [{ label: 'Build Checklist', path: `${DOC_ROOT}/docs/BUILD_CHECKLIST.md` }],
      },
      {
        id: 'manual-confirm-import',
        title: '人工确认入库',
        category: '智能录入',
        priority: 'P1',
        status: 'TODO',
        maturity: 'M0',
        progress: 0,
        productValue: '保证 AI 识别只是填表，最终数据由用户确认。',
        currentEvidence: ['产品原则已明确'],
        nextActions: ['复用持仓快照草稿保存 API'],
        backendState: '未开始',
        frontendState: '未开始',
        dataOwnership: 'DB',
        risks: ['缺少确认步骤会污染正式数据'],
        docLinks: [{ label: 'Product Blueprint', path: `${DOC_ROOT}/docs/PRODUCT_BLUEPRINT.md` }],
      },
    ],
  },
  {
    id: 'quant-analysis',
    title: '量化分析',
    category: '量化分析',
    priority: 'P2',
    status: 'TODO',
    maturity: 'M0',
    progress: 0,
    productValue: '从记录工具升级到可验证策略、指标和回测系统。',
    currentEvidence: ['早期架构文档已设计'],
    nextActions: ['先做日 K CSV 导入，再做指标计算'],
    backendState: '未开始',
    frontendState: '未开始',
    dataOwnership: 'DB',
    risks: ['过早做策略会分散当前记录闭环建设'],
    docLinks: [
      { label: 'Roadmap', path: `${DOC_ROOT}/docs/DEVELOPMENT_ROADMAP.md` },
      { label: 'Backtest Design', path: `${DOC_ROOT}/docs/BACKTEST_ENGINE_DESIGN.md` },
    ],
    children: [
      {
        id: 'daily-bar-import',
        title: '日 K 数据导入',
        category: '量化分析',
        priority: 'P2',
        status: 'TODO',
        maturity: 'M0',
        progress: 0,
        productValue: '沉淀行情数据，支撑指标和回测。',
        currentEvidence: ['未开始'],
        nextActions: ['设计 CSV 导入表和接口'],
        backendState: '未开始',
        frontendState: '未开始',
        dataOwnership: 'DB',
        risks: ['数据质量直接影响指标和回测'],
        docLinks: [{ label: 'Roadmap', path: `${DOC_ROOT}/docs/DEVELOPMENT_ROADMAP.md` }],
      },
      {
        id: 'technical-indicators',
        title: '技术指标',
        category: '量化分析',
        priority: 'P2',
        status: 'TODO',
        maturity: 'M0',
        progress: 0,
        productValue: '计算 MA、MACD、RSI、BOLL 等辅助分析指标。',
        currentEvidence: ['未开始'],
        nextActions: ['先实现 MA/MACD/RSI/BOLL'],
        backendState: '未开始',
        frontendState: '未开始',
        dataOwnership: 'DERIVED',
        risks: ['必须避免未来函数'],
        docLinks: [{ label: 'Architecture', path: `${DOC_ROOT}/docs/ARCHITECTURE.md` }],
      },
      {
        id: 'strategy-signal',
        title: '策略信号',
        category: '量化分析',
        priority: 'P2',
        status: 'TODO',
        maturity: 'M0',
        progress: 0,
        productValue: '把规则策略输出为可解释信号和风险提示。',
        currentEvidence: ['未开始'],
        nextActions: ['先做均线趋势 + 成交量过滤'],
        backendState: '未开始',
        frontendState: '未开始',
        dataOwnership: 'DB',
        risks: ['信号必须表达为辅助参考，不是买卖命令'],
        docLinks: [{ label: 'Strategy Design', path: `${DOC_ROOT}/docs/STRATEGY_PLUGIN_DESIGN.md` }],
      },
      {
        id: 'backtest-engine',
        title: '回测引擎',
        category: '量化分析',
        priority: 'P2',
        status: 'TODO',
        maturity: 'M0',
        progress: 0,
        productValue: '验证策略规则在历史数据上的表现和风险。',
        currentEvidence: ['设计文档已存在'],
        nextActions: ['实现简化日线回测'],
        backendState: '未开始',
        frontendState: '未开始',
        dataOwnership: 'DERIVED',
        risks: ['必须纳入手续费、滑点、T+1'],
        docLinks: [{ label: 'Backtest Design', path: `${DOC_ROOT}/docs/BACKTEST_ENGINE_DESIGN.md` }],
      },
      {
        id: 'report-output',
        title: '报告输出',
        category: '量化分析',
        priority: 'P2',
        status: 'TODO',
        maturity: 'M0',
        progress: 0,
        productValue: '输出可回看、可比较的策略和复盘报告。',
        currentEvidence: ['未开始'],
        nextActions: ['先输出 JSON/页面报告'],
        backendState: '未开始',
        frontendState: '未开始',
        dataOwnership: 'DERIVED',
        risks: ['报告不能包装成收益承诺'],
        docLinks: [{ label: 'Product Blueprint', path: `${DOC_ROOT}/docs/PRODUCT_BLUEPRINT.md` }],
      },
    ],
  },
];
